<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite0dfc701f39261d478388b653ab8936d
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'LINE\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LINE\\' => 
        array (
            0 => __DIR__ . '/..' . '/linecorp/line-bot-sdk/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite0dfc701f39261d478388b653ab8936d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite0dfc701f39261d478388b653ab8936d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite0dfc701f39261d478388b653ab8936d::$classMap;

        }, null, ClassLoader::class);
    }
}
